version: '3.8'
services:             
    mangochat-mysql:
        image: mysql:8.0
        container_name: mangochat-mysql   #changed container name
        restart: always
        environment:
            MYSQL_DATABASE: 'mangochat'   #changed database name
            MYSQL_USER: 'mango'  #changed user name                           
            MYSQL_PASSWORD: 'COSC310=mcpw'  #changed password         
            MYSQL_ROOT_PASSWORD: 'mangorootpw'   #changed root password
        ports:
            - '3306:3306'
        expose:
            - '3306'   
        volumes:
            - mysql-db:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d #changed the path to find the sql schema on local machine
        networks:
            networkmangoChat: #changed network configuration
                aliases:
                    - mangochat_mysql      
volumes: 
    #mangochat-db:
    mysql-db:
networks:
    networkmangoChat:
